name: Daily SWPPP and Weather Update

on:
  schedule:
    - cron: '0 12 * * *' # Runs at 7:00 AM EST every day
  workflow_dispatch: # Allows you to run it manually

jobs:
  update-dashboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install requests PyGithub

      - name: Run Update Script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # This assumes you have an updater.py in your repo 
          # to fetch USGS and Satellite data
          python scripts/updater.py 

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add data/site_status.json
          git commit -m "Automated Site Status Update" || exit 0
          git push
